name: Check uMod Plugin Updates

on:
  schedule:
    - cron: '0 0 * * *' # Check every day at midnight (UTC)
  workflow_dispatch: # Allow manual trigger

jobs:
  check-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch current version from uMod
        id: fetch_umod
        run: |
          UMOD_API_URL="https://umod.org/plugins/discord-wipe.json"
          
          response=$(curl -s $UMOD_API_URL)
          latest_version=$(echo "$response" | jq -r '.latest_release_version')
          download_url=$(echo "$response" | jq -r '.download_url')

          echo "Latest version on uMod: $latest_version"
          echo "Download URL: $download_url"

          echo "latest_version=$latest_version" >> $GITHUB_ENV
          echo "download_url=$download_url" >> $GITHUB_ENV

      - name: Get latest GitHub release version
        id: get_latest_release
        run: |
          git fetch --tags
          latest_tag=$(git describe --tags $(git rev-list --tags --max-count=1) 2>/dev/null || echo "v0.0.0")
          current_version=${latest_tag#v}

          echo "Latest GitHub release version: $current_version"
          echo "current_version=$current_version" >> $GITHUB_ENV

      - name: Compare versions
        run: |
          current_version="${{ env.current_version }}"
          latest_version="${{ env.latest_version }}"

          echo "Current version in repo: $current_version"
          echo "Latest version from uMod: $latest_version"
          
          if [ "$current_version" != "$latest_version" ]; then
            echo "New version found: $latest_version"
            echo "new_version=true" >> $GITHUB_ENV
          else
            echo "No new version"
            echo "new_version=false" >> $GITHUB_ENV

      - name: Download new plugin version
        if: env.new_version == 'true'
        run: |
          download_url="${{ env.download_url }}"
          curl -o DiscordWipe.cs "$download_url"
          
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add DiscordWipe.cs
          git commit -m "v${{ env.latest_version }}"
          git push

      - name: Create GitHub release
        if: env.new_version == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create "v${{ env.latest_version }}" DiscordWipe.cs \
            --title "DiscordWipe v${{ env.latest_version }}" \
            --notes "Automatic release of new version from uMod."
